import React, { useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { gsap } from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import { ScrollSmoother } from 'gsap/ScrollSmoother'
import { Howl } from 'howler'
import { wedding } from './data/wedding'
import './styles.css'
gsap.registerPlugin(ScrollTrigger, ScrollSmoother)

const Motif = ({ className = '' }) => <svg className={`motif ${className}`} viewBox="0 0 240 56" aria-hidden="true"><path d="M5 28C35 4 50 4 80 28s45 24 75 0 45-24 80 0" fill="none" stroke="currentColor" strokeWidth="1"/><path d="M42 24c0 18 16 18 16 0M120 24c0 18 16 18 16 0M198 24c0 18 16 18 16 0" fill="none" stroke="currentColor"/><circle cx="50" cy="44" r="4"/><circle cx="128" cy="44" r="4"/><circle cx="206" cy="44" r="4"/></svg>
const Diya = ({className=''}) => <span className={`diya ${className}`}><i/></span>
function Countdown(){ const [left,setLeft]=useState({}); useEffect(()=>{const tick=()=>{let d=Math.max(0,new Date(wedding.date)-Date.now()); setLeft({Days:Math.floor(d/864e5),Hours:Math.floor(d/36e5)%24,Minutes:Math.floor(d/6e4)%60,Seconds:Math.floor(d/1e3)%60})};tick();let t=setInterval(tick,1000);return()=>clearInterval(t)},[]); return <div className="countdown" aria-label="Countdown to wedding">{Object.entries(left).map(([k,v])=><div key={k}><b>{String(v).padStart(2,'0')}</b><small>{k}</small></div>)}</div> }
function ScratchCard(){const ref=useRef();const [done,setDone]=useState(false); useEffect(()=>{let c=ref.current,ctx=c.getContext('2d'),draw=false,last; const size=()=>{let r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;ctx.scale(d,d);ctx.globalCompositeOperation='source-over';let g=ctx.createLinearGradient(0,0,r.width,r.height);g.addColorStop(0,'#a9742a');g.addColorStop(.5,'#e2b866');g.addColorStop(1,'#6c3519');ctx.fillStyle=g;ctx.fillRect(0,0,r.width,r.height);ctx.fillStyle='rgba(255,246,212,.55)';ctx.font='14px serif';ctx.textAlign='center';ctx.fillText('SCRATCH WITH LOVE',r.width/2,r.height/2)}; size();addEventListener('resize',size); const point=e=>{let r=c.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:p.clientX-r.left,y:p.clientY-r.top}};const scratch=e=>{if(!draw)return;e.preventDefault();let p=point(e);ctx.globalCompositeOperation='destination-out';ctx.lineWidth=38;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p;let a=ctx.getImageData(0,0,c.width,c.height).data,clear=0;for(let i=3;i<a.length;i+=80)if(a[i]<20)clear++;if(clear/(a.length/80)>.32){ctx.clearRect(0,0,c.width,c.height);setDone(true)}};const start=e=>{draw=true;last=point(e)};const end=()=>draw=false;c.addEventListener('pointerdown',start);c.addEventListener('pointermove',scratch);addEventListener('pointerup',end);return()=>{removeEventListener('resize',size);c.removeEventListener('pointerdown',start);c.removeEventListener('pointermove',scratch);removeEventListener('pointerup',end)}},[]);return <section className={`reveal ${done?'revealed':''}`} aria-labelledby="date-title"><div className="invite-card"><p className="eyebrow">A date to remember</p><Motif/><h2 id="date-title">11 <em>December</em> 2026</h2><p className="couple-line">{wedding.couple}</p><canvas ref={ref} aria-label="Scratch to reveal wedding date" role="img"/><span className="scratch-hint">{done?'With love, revealed':'Touch and scratch to reveal'}</span></div><Countdown/></section>}
function TempleScene(){const root=useRef();useEffect(()=>{const el=root.current,reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduce)return;let ctx=gsap.context(()=>{let tl=gsap.timeline({scrollTrigger:{trigger:el,start:'top top',end:'+=260%',scrub:1,pin:true,anticipatePin:1}});tl.fromTo('.temple',{opacity:.2,scale:.86},{opacity:1,scale:1,duration:1}).to('.doors .left',{xPercent:-94,duration:1},.8).to('.doors .right',{xPercent:94,duration:1},.8).to('.temple',{scale:1.24,yPercent:6,duration:1},1.3).to('.temple-world',{backgroundColor:'#5a1d1d',duration:.8},1.8).to('.mandap',{opacity:1,scale:1,duration:1},2).to('.temple',{opacity:.18,duration:.8},2.1).to('.scene-copy',{opacity:1,y:0,duration:.5},2.4);gsap.to('.flame',{scaleY:1.3,repeat:-1,yoyo:true,stagger:.14,duration:.7});},el);return()=>ctx.revert()},[]);return <section ref={root} className="temple-world" aria-label="A journey from temple to mandap"><div className="stars">✦　·　✦　·　✦</div><div className="toran"><Motif/></div><div className="temple"><div className="shikhara">✦</div><div className="arch"/><div className="pillar p1"/><div className="pillar p2"/><div className="doors"><div className="door left"/><div className="door right"/></div></div><div className="mandap"><div className="mandap-roof"><Motif/></div><div className="mandap-pillars"><i/><i/><i/><i/></div><div className="rangoli">✦</div></div><div className="scene-diyas"><Diya/><Diya/><Diya/><Diya/></div><div className="scene-copy"><p className="eyebrow">The celebration unfolds</p><h2>Welcome to our<br/><em>wedding square</em></h2><p>{wedding.dateLabel} · {wedding.muhurat}</p></div></section>}
function Events(){return <section className="events" id="journey"><header><p className="eyebrow">The wedding journey</p><h2>Four days, one <em>beautiful beginning</em></h2></header><ol>{wedding.events.map((e,i)=><li key={e.name}><div className="event-date"><b>{e.date}</b><span>{e.month}</span></div><article><p className="eyebrow">{e.day} · {e.gujarati}</p><h3>{e.name}</h3><p>{e.description}</p><footer><span>{e.time}</span><a href={e.map} target="_blank" rel="noreferrer">{e.venue} ↗</a></footer><small>{e.address} · Dress code: {e.dress}</small></article></li>)}</ol></section>}
function Gallery(){return <section className="gallery"><header><p className="eyebrow">A glimpse of us</p><h2>Written in <em>golden light</em></h2></header><div className="gallery-track">{wedding.gallery.map((g,i)=><figure className={g.tone} key={g.title}><div className="portrait"><span>{i===0?'K':'J'}</span></div><figcaption>{g.title}</figcaption></figure>)}</div></section>}
function Music(){const [on,setOn]=useState(false);let sound=useRef();useEffect(()=>()=>sound.current?.unload(),[]);const toggle=()=>{if(!sound.current)sound.current=new Howl({src:[wedding.music],loop:true,volume:0,onloaderror:()=>setOn(false)});if(on){sound.current.fade(.28,0,350);setTimeout(()=>sound.current.pause(),350);setOn(false)}else{sound.current.play();sound.current.fade(0,.28,600);setOn(true)}};return <button className={`music ${on?'playing':''}`} onClick={toggle} aria-pressed={on}><i/><i/><i/> <span>Music {on?'on':'off'}</span></button>}
function App(){useEffect(()=>{const desktop=matchMedia('(min-width: 768px)').matches && !matchMedia('(prefers-reduced-motion: reduce)').matches; const smoother=desktop ? ScrollSmoother.create({wrapper:'#smooth-wrapper',content:'#smooth-content',smooth:0.7,effects:false,normalizeScroll:true}) : null; let started=false;const start=()=>{if(!started){started=true;document.documentElement.classList.add('entered')}};addEventListener('scroll',start,{once:true,passive:true});return()=>{removeEventListener('scroll',start);smoother?.kill()}},[]);return <><Music/><div id="smooth-wrapper"><main id="smooth-content"><section className="hero"><div className="hero-particles">✦　·　✦　·　✦</div><Motif/><p className="invocation">{wedding.invocation}</p><h1><span>Krutik</span><i>&</i><span>Jahanvee</span></h1><p className="hero-date">11 · 12 · 2026</p><div className="hero-diyas"><Diya/><Diya/></div><a href="#temple" className="enter">Scroll to enter <b>↓</b></a></section><div id="temple"><TempleScene/></div><ScratchCard/><Events/><Gallery/><section className="closing"><Motif/><p className="eyebrow">With the blessings of our families</p><h2>Come, celebrate<br/><em>love with us.</em></h2><p>{wedding.location.venue}<br/>{wedding.location.address}</p><div><a className="button" href={wedding.location.map} target="_blank" rel="noreferrer">Get directions</a><a className="text-link" href={wedding.rsvp.whatsapp} target="_blank" rel="noreferrer">RSVP via WhatsApp ↗</a></div></section></main></div></>}; createRoot(document.getElementById('root')).render(<App/>)
